Fix error during setup master node
Because of changes in fuel-qa deploying with `./deploy_env.sh` was
failed with:
```
AssertionError: Command awk '/COLLECTOR.*URL/'
/usr/lib/python2.7/site-packages/nailgun/settings.yaml returned exit
code "2", but expected "0". Output: []; ["awk: fatal: cannot open file
`/usr/lib/python2.7/site-packages/nailgun/settings.yaml' for reading (No
such file or directory)\n"]
```